### ISSUE TITLE
install.packages() fails

### ISSUE THREAD

**Issue by MattBixley** [nesi/eri-ood-rstudio-server-app#8]
install.packages() returns

`Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘devtools’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages`

it can't see the web?

**Comment by MattBixley** [comment]
Thomas - There is a squid proxy we can use

`export https_proxy="https://10.1.112.161:3128/"`
`export https_proxy="http://10.1.112.161:3128/"`

edit: did not resolve issue when placed in `script.sh.erb` for now.

**Comment by MattBixley** [comment]
from blairo

Yeah, I mentioned it might be HTTP_PROXY / http_proxy environment variables needing to be set

This would need to happen before the RStudio process is invoked, so that it inherits / can see them though

**Comment by MattBixley** [comment]
https://support.posit.co/hc/en-us/articles/226914208-Installing-packages-on-RStudio-Connect-from-behind-a-proxy

**Comment by MattBixley** [comment]
Ben Taylor
  1 minute ago
On the 10.27 range we have an overly permissive allow all web out rule we intend to roll back when we prioritise it, 10.1 wasn't included hence it becoming a block

**Comment by DininduSenanayake** [comment]
Fixed in. Correct fix is on https://github.com/nesi/eri-ood-rstudio-server-app/commit/9d78d9dd07ea100d86af967e74141f96f15ddd0c

**Comment by MattBixley** [comment]
Does not work for Me due to my environment setup, should work for users
